name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: action/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Create alur_sistem_apotek.txt
      run: |
        echo "1" > alur_sistem_apotek.txt
        echo "1" >> alur_sistem_apotek.txt
        echo "2" >> alur_sistem_apotek.txt
        echo "4" >> alur_sistem_apotek.txt
        echo "2" >> alur_sistem_apotek.txt
        echo "1" >> alur_sistem_apotek.txt
        echo "Paracetamol" >> alur_sistem_apotek.txt
        echo "15000" >> alur_sistem_apotek.txt
        echo "n" >> alur_sistem_apotek.txt
        echo "11" >> alur_sistem_apotek.txt
        echo "3" >> alur_sistem_apotek.txt
        echo "1" >> alur_sistem_apotek.txt
        echo "Paracetamol" >> alur_sistem_apotek.txt
        echo "1" >> alur_sistem_apotek.txt
        echo "5" >> alur_sistem_apotek.txt
        echo "4" >> alur_sistem_apotek.txt
    - name: Compile C++ code
      run: g++ -o main Apotek.cpp

    - name: Run the program with input.txt
      run: ./main < alur_sistem_apotek.txt
